#ifndef SOCKETTCPSERVER_GLOBAL_H
#define SOCKETTCPSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOCKETTCPSERVER_LIBRARY)
#  define SOCKETTCPSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOCKETTCPSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOCKETTCPSERVER_GLOBAL_H
